baseURL = 'https://jplochocki.github.io/'
languageCode = 'pl'
defaultContentLanguage = 'pl'
title = '/home/systemik/blog'
theme = 'beautifulhugo'
staticDir = ['static', 'static/post']

[Params]
  GoogleAnalyticsID = 'G-KETRV3SXRJ'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    lineNos = true
